version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: ${PASS}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS}
      MYSQL_DATABASE: redmine
