version: '3'

services:
  sshserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${SSH_PORT}:22
      - ${HTTP_PORT}:80
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
